extends:
  - requarks
  - plugin:vue/strongly-recommended
  - plugin:cypress/recommended
env:
  node: true
  jest: true
parserOptions:
  parser: babel-eslint
  ecmaVersion: 2017
  allowImportExportEverywhere: true
globals:
  document: false
  navigator: false
  window: false
  WIKI: true
  siteLangs: true
  siteConfig: true
  graphQL: true
rules:
  vue/custom-event-name-casing: off
  vue/no-arrow-functions-in-watch: off
  no-useless-escape: off
  import/no-duplicates: off
